/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpackage.AdminWindowPanels;

import mainpackage.ApplicationWindow;

/**
 *
 * @author cosmi
 */
public class AdminMainPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    
    private final ApplicationWindow appWindow;
    
    public AdminMainPanel(ApplicationWindow appWindow) {
        
        this.appWindow = appWindow;
        initComponents();
        initActionListeners();
        
    }

    private void initActionListeners()
    {        
        loginButton.addActionListener(appWindow.appActionListener().getButtonClickListener());
        backCAButton.addActionListener(appWindow.appActionListener().getButtonClickListener());
        createNewAccountButton.addActionListener(appWindow.appActionListener().getButtonClickListener());
        createAccountButton.addActionListener(appWindow.appActionListener().getButtonClickListener());
        menusAdminButton.addActionListener(appWindow.appActionListener().getButtonClickListener());
        categoriesAdminButton.addActionListener(appWindow.appActionListener().getButtonClickListener());
        productsAdminButton.addActionListener(appWindow.appActionListener().getButtonClickListener());
        ingredientsAdminButton.addActionListener(appWindow.appActionListener().getButtonClickListener());
        menusCategoriesAdminButton.addActionListener(appWindow.appActionListener().getButtonClickListener());
        categoriesProductsAdminButton.addActionListener(appWindow.appActionListener().getButtonClickListener());
        
        recipesAdminButton.addActionListener(appWindow.appActionListener().getButtonClickListener());
        productTypeAdminButton.addActionListener(appWindow.appActionListener().getButtonClickListener());
        ordersAdminButton.addActionListener(appWindow.appActionListener().getButtonClickListener());
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        loginMainPanel = new javax.swing.JPanel();
        loginPanels = new javax.swing.JPanel();
        adminLoginPanel = new javax.swing.JPanel();
        idAdminTextField = new javax.swing.JTextField();
        numeContTextField = new javax.swing.JTextField();
        parolaContTextField = new javax.swing.JPasswordField();
        idAdminLabel = new javax.swing.JLabel();
        numeContLabel = new javax.swing.JLabel();
        parolaContLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        createNewAccountButton = new javax.swing.JButton();
        createAccountPanel = new javax.swing.JPanel();
        idAdminCALabel = new javax.swing.JLabel();
        numeContCALabel = new javax.swing.JLabel();
        parolaContCAtLabel = new javax.swing.JLabel();
        parolaContCAtLabel1 = new javax.swing.JLabel();
        idAdminCATextField = new javax.swing.JTextField();
        numeContCATextField = new javax.swing.JTextField();
        parolaContCATextField = new javax.swing.JPasswordField();
        repParolaContCATextField1 = new javax.swing.JPasswordField();
        backCAButton = new javax.swing.JButton();
        createAccountButton = new javax.swing.JButton();
        adminMenuPanel = new javax.swing.JSplitPane();
        leftSideAdminPanel = new javax.swing.JPanel();
        menusAdminButton = new javax.swing.JButton();
        categoriesAdminButton = new javax.swing.JButton();
        productsAdminButton = new javax.swing.JButton();
        ingredientsAdminButton = new javax.swing.JButton();
        menusCategoriesAdminButton = new javax.swing.JButton();
        categoriesProductsAdminButton = new javax.swing.JButton();
        recipesAdminButton = new javax.swing.JButton();
        productTypeAdminButton = new javax.swing.JButton();
        ordersAdminButton = new javax.swing.JButton();
        rightSideAdminPanel = new javax.swing.JPanel();
        defaultPanel = new javax.swing.JPanel();
        menusAdminPanel = new mainpackage.AdminWindowPanels.MenusAdminPanel();
        manusTables = new javax.swing.JTable();
        categoriesAdminPanel1 = new mainpackage.AdminWindowPanels.CategoriesAdminPanel();
        menusCategoriesAdminPanel = new mainpackage.AdminWindowPanels.MenusCategoriesAdminPanel();
        productsAdminPanel = new mainpackage.AdminWindowPanels.ProductsAdminPanel();
        categoriesProductsAdminPanel = new mainpackage.AdminWindowPanels.CategoriesProductsAdminPanel();
        ingredientsAdminPanel = new mainpackage.AdminWindowPanels.IngredientsAdminPanel();
        recipesAdminPanel = new mainpackage.AdminWindowPanels.RecipesAdminPanel();
        productTypeAdminPanel = new mainpackage.AdminWindowPanels.ProductTypeAdminPanel();
        ordersAdminPanel = new mainpackage.AdminWindowPanels.OrdersAdminPanel();

        setLayout(new java.awt.CardLayout());

        loginMainPanel.setPreferredSize(new java.awt.Dimension(1280, 720));

        loginPanels.setBackground(new java.awt.Color(102, 0, 51));
        loginPanels.setLayout(new java.awt.CardLayout());

        adminLoginPanel.setBackground(new java.awt.Color(102, 51, 0));
        adminLoginPanel.setForeground(new java.awt.Color(102, 0, 51));

        idAdminTextField.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N

        numeContTextField.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N

        idAdminLabel.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        idAdminLabel.setForeground(new java.awt.Color(255, 255, 255));
        idAdminLabel.setText("ID ADMIN:");

        numeContLabel.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        numeContLabel.setForeground(new java.awt.Color(255, 255, 255));
        numeContLabel.setText("NUME CONT:");

        parolaContLabel.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        parolaContLabel.setForeground(new java.awt.Color(255, 255, 255));
        parolaContLabel.setText("PAROLA:");

        loginButton.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        loginButton.setText("Logare");

        createNewAccountButton.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        createNewAccountButton.setText("Creare cont nou");

        javax.swing.GroupLayout adminLoginPanelLayout = new javax.swing.GroupLayout(adminLoginPanel);
        adminLoginPanel.setLayout(adminLoginPanelLayout);
        adminLoginPanelLayout.setHorizontalGroup(
            adminLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminLoginPanelLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addGroup(adminLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminLoginPanelLayout.createSequentialGroup()
                        .addGroup(adminLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numeContLabel)
                            .addComponent(idAdminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parolaContLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(adminLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(idAdminTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(numeContTextField)
                            .addComponent(parolaContTextField)))
                    .addGroup(adminLoginPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(adminLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createNewAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(224, 224, 224))
        );
        adminLoginPanelLayout.setVerticalGroup(
            adminLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminLoginPanelLayout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(adminLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idAdminTextField)
                    .addComponent(idAdminLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(adminLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numeContTextField)
                    .addComponent(numeContLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(adminLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parolaContLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(adminLoginPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(parolaContTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createNewAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );

        loginPanels.add(adminLoginPanel, "card1");

        createAccountPanel.setBackground(new java.awt.Color(102, 51, 0));
        createAccountPanel.setForeground(new java.awt.Color(102, 0, 51));

        idAdminCALabel.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        idAdminCALabel.setForeground(new java.awt.Color(255, 255, 255));
        idAdminCALabel.setText("ID ADMIN:");

        numeContCALabel.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        numeContCALabel.setForeground(new java.awt.Color(255, 255, 255));
        numeContCALabel.setText("NUME CONT:");

        parolaContCAtLabel.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        parolaContCAtLabel.setForeground(new java.awt.Color(255, 255, 255));
        parolaContCAtLabel.setText("PAROLA:");

        parolaContCAtLabel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        parolaContCAtLabel1.setForeground(new java.awt.Color(255, 255, 255));
        parolaContCAtLabel1.setText("REPETA PAROLA:");

        idAdminCATextField.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N

        numeContCATextField.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N

        backCAButton.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        backCAButton.setText("Înapoi");

        createAccountButton.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        createAccountButton.setText("Creare cont");

        javax.swing.GroupLayout createAccountPanelLayout = new javax.swing.GroupLayout(createAccountPanel);
        createAccountPanel.setLayout(createAccountPanelLayout);
        createAccountPanelLayout.setHorizontalGroup(
            createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAccountPanelLayout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createAccountPanelLayout.createSequentialGroup()
                        .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(parolaContCAtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numeContCALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(createAccountPanelLayout.createSequentialGroup()
                                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idAdminCALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(parolaContCAtLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)))
                        .addGap(32, 32, 32)
                        .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(idAdminCATextField, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(numeContCATextField)
                            .addComponent(parolaContCATextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(repParolaContCATextField1, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(createAccountPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backCAButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(154, 154, 154))
        );
        createAccountPanelLayout.setVerticalGroup(
            createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAccountPanelLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idAdminCATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idAdminCALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeContCATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeContCALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parolaContCAtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(createAccountPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(parolaContCATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parolaContCAtLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repParolaContCATextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backCAButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );

        loginPanels.add(createAccountPanel, "card2");

        javax.swing.GroupLayout loginMainPanelLayout = new javax.swing.GroupLayout(loginMainPanel);
        loginMainPanel.setLayout(loginMainPanelLayout);
        loginMainPanelLayout.setHorizontalGroup(
            loginMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginMainPanelLayout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(loginPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(328, Short.MAX_VALUE))
        );
        loginMainPanelLayout.setVerticalGroup(
            loginMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginMainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );

        add(loginMainPanel, "card1");

        adminMenuPanel.setDividerLocation(210);
        adminMenuPanel.setPreferredSize(new java.awt.Dimension(1280, 720));

        leftSideAdminPanel.setBackground(new java.awt.Color(102, 51, 0));
        leftSideAdminPanel.setLayout(new java.awt.GridBagLayout());

        menusAdminButton.setBackground(new java.awt.Color(204, 204, 204));
        menusAdminButton.setText("Meniuri");
        menusAdminButton.setActionCommand("ButonMeniuAdmin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 46;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        leftSideAdminPanel.add(menusAdminButton, gridBagConstraints);

        categoriesAdminButton.setText("Categorii");
        categoriesAdminButton.setActionCommand("ButonMeniuAdmin");
        categoriesAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriesAdminButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 46;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        leftSideAdminPanel.add(categoriesAdminButton, gridBagConstraints);

        productsAdminButton.setText("Produse");
        productsAdminButton.setActionCommand("ButonMeniuAdmin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 46;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        leftSideAdminPanel.add(productsAdminButton, gridBagConstraints);

        ingredientsAdminButton.setText("Ingrediente");
        ingredientsAdminButton.setActionCommand("ButonMeniuAdmin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 46;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        leftSideAdminPanel.add(ingredientsAdminButton, gridBagConstraints);

        menusCategoriesAdminButton.setText("Meniuri <-> Categorii");
        menusCategoriesAdminButton.setActionCommand("ButonMeniuAdmin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 46;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        leftSideAdminPanel.add(menusCategoriesAdminButton, gridBagConstraints);

        categoriesProductsAdminButton.setText("Categorii <-> Produse");
        categoriesProductsAdminButton.setActionCommand("ButonMeniuAdmin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 46;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        leftSideAdminPanel.add(categoriesProductsAdminButton, gridBagConstraints);

        recipesAdminButton.setText("Retete");
        recipesAdminButton.setActionCommand("ButonMeniuAdmin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 46;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        leftSideAdminPanel.add(recipesAdminButton, gridBagConstraints);

        productTypeAdminButton.setText("Tipuri aliment");
        productTypeAdminButton.setActionCommand("ButonMeniuAdmin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 46;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        leftSideAdminPanel.add(productTypeAdminButton, gridBagConstraints);

        ordersAdminButton.setText("Comenzi");
        ordersAdminButton.setActionCommand("ButonMeniuAdmin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.ipady = 49;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        leftSideAdminPanel.add(ordersAdminButton, gridBagConstraints);

        adminMenuPanel.setLeftComponent(leftSideAdminPanel);

        rightSideAdminPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout defaultPanelLayout = new javax.swing.GroupLayout(defaultPanel);
        defaultPanel.setLayout(defaultPanelLayout);
        defaultPanelLayout.setHorizontalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
        );
        defaultPanelLayout.setVerticalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        rightSideAdminPanel.add(defaultPanel, "defaultCard");

        manusTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "nr_meniu", "nume_meniu", "data_creare", "detalii_suplimentare"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });

        javax.swing.GroupLayout menusAdminPanelLayout = new javax.swing.GroupLayout(menusAdminPanel);
        menusAdminPanel.setLayout(menusAdminPanelLayout);
        menusAdminPanelLayout.setHorizontalGroup(
            menusAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
            .addGroup(menusAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menusAdminPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(manusTables, javax.swing.GroupLayout.PREFERRED_SIZE, 1063, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        menusAdminPanelLayout.setVerticalGroup(
            menusAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
            .addGroup(menusAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menusAdminPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(manusTables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        rightSideAdminPanel.add(menusAdminPanel, "Meniuri");

        javax.swing.GroupLayout categoriesAdminPanel1Layout = new javax.swing.GroupLayout(categoriesAdminPanel1);
        categoriesAdminPanel1.setLayout(categoriesAdminPanel1Layout);
        categoriesAdminPanel1Layout.setHorizontalGroup(
            categoriesAdminPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
        );
        categoriesAdminPanel1Layout.setVerticalGroup(
            categoriesAdminPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        rightSideAdminPanel.add(categoriesAdminPanel1, "Categorii");

        javax.swing.GroupLayout menusCategoriesAdminPanelLayout = new javax.swing.GroupLayout(menusCategoriesAdminPanel);
        menusCategoriesAdminPanel.setLayout(menusCategoriesAdminPanelLayout);
        menusCategoriesAdminPanelLayout.setHorizontalGroup(
            menusCategoriesAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
        );
        menusCategoriesAdminPanelLayout.setVerticalGroup(
            menusCategoriesAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        rightSideAdminPanel.add(menusCategoriesAdminPanel, "Meniuri <-> Categorii");

        javax.swing.GroupLayout productsAdminPanelLayout = new javax.swing.GroupLayout(productsAdminPanel);
        productsAdminPanel.setLayout(productsAdminPanelLayout);
        productsAdminPanelLayout.setHorizontalGroup(
            productsAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
        );
        productsAdminPanelLayout.setVerticalGroup(
            productsAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        rightSideAdminPanel.add(productsAdminPanel, "Produse");

        javax.swing.GroupLayout categoriesProductsAdminPanelLayout = new javax.swing.GroupLayout(categoriesProductsAdminPanel);
        categoriesProductsAdminPanel.setLayout(categoriesProductsAdminPanelLayout);
        categoriesProductsAdminPanelLayout.setHorizontalGroup(
            categoriesProductsAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
        );
        categoriesProductsAdminPanelLayout.setVerticalGroup(
            categoriesProductsAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        rightSideAdminPanel.add(categoriesProductsAdminPanel, "Categorii <-> Produse");

        javax.swing.GroupLayout ingredientsAdminPanelLayout = new javax.swing.GroupLayout(ingredientsAdminPanel);
        ingredientsAdminPanel.setLayout(ingredientsAdminPanelLayout);
        ingredientsAdminPanelLayout.setHorizontalGroup(
            ingredientsAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
        );
        ingredientsAdminPanelLayout.setVerticalGroup(
            ingredientsAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        rightSideAdminPanel.add(ingredientsAdminPanel, "Ingrediente");

        javax.swing.GroupLayout recipesAdminPanelLayout = new javax.swing.GroupLayout(recipesAdminPanel);
        recipesAdminPanel.setLayout(recipesAdminPanelLayout);
        recipesAdminPanelLayout.setHorizontalGroup(
            recipesAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
        );
        recipesAdminPanelLayout.setVerticalGroup(
            recipesAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        rightSideAdminPanel.add(recipesAdminPanel, "Retete");

        javax.swing.GroupLayout productTypeAdminPanelLayout = new javax.swing.GroupLayout(productTypeAdminPanel);
        productTypeAdminPanel.setLayout(productTypeAdminPanelLayout);
        productTypeAdminPanelLayout.setHorizontalGroup(
            productTypeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
        );
        productTypeAdminPanelLayout.setVerticalGroup(
            productTypeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        rightSideAdminPanel.add(productTypeAdminPanel, "Tipuri aliment");

        javax.swing.GroupLayout ordersAdminPanelLayout = new javax.swing.GroupLayout(ordersAdminPanel);
        ordersAdminPanel.setLayout(ordersAdminPanelLayout);
        ordersAdminPanelLayout.setHorizontalGroup(
            ordersAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
        );
        ordersAdminPanelLayout.setVerticalGroup(
            ordersAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        rightSideAdminPanel.add(ordersAdminPanel, "Comenzi");

        adminMenuPanel.setRightComponent(rightSideAdminPanel);

        add(adminMenuPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void categoriesAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriesAdminButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriesAdminButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminLoginPanel;
    private javax.swing.JSplitPane adminMenuPanel;
    private javax.swing.JButton backCAButton;
    private javax.swing.JButton categoriesAdminButton;
    private mainpackage.AdminWindowPanels.CategoriesAdminPanel categoriesAdminPanel1;
    private javax.swing.JButton categoriesProductsAdminButton;
    private mainpackage.AdminWindowPanels.CategoriesProductsAdminPanel categoriesProductsAdminPanel;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JPanel createAccountPanel;
    private javax.swing.JButton createNewAccountButton;
    private javax.swing.JPanel defaultPanel;
    private javax.swing.JLabel idAdminCALabel;
    private javax.swing.JTextField idAdminCATextField;
    private javax.swing.JLabel idAdminLabel;
    private javax.swing.JTextField idAdminTextField;
    private javax.swing.JButton ingredientsAdminButton;
    private mainpackage.AdminWindowPanels.IngredientsAdminPanel ingredientsAdminPanel;
    private javax.swing.JPanel leftSideAdminPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginMainPanel;
    public javax.swing.JPanel loginPanels;
    private javax.swing.JTable manusTables;
    private javax.swing.JButton menusAdminButton;
    private mainpackage.AdminWindowPanels.MenusAdminPanel menusAdminPanel;
    private javax.swing.JButton menusCategoriesAdminButton;
    private mainpackage.AdminWindowPanels.MenusCategoriesAdminPanel menusCategoriesAdminPanel;
    private javax.swing.JLabel numeContCALabel;
    private javax.swing.JTextField numeContCATextField;
    private javax.swing.JLabel numeContLabel;
    private javax.swing.JTextField numeContTextField;
    private javax.swing.JButton ordersAdminButton;
    private mainpackage.AdminWindowPanels.OrdersAdminPanel ordersAdminPanel;
    private javax.swing.JPasswordField parolaContCATextField;
    private javax.swing.JLabel parolaContCAtLabel;
    private javax.swing.JLabel parolaContCAtLabel1;
    private javax.swing.JLabel parolaContLabel;
    private javax.swing.JPasswordField parolaContTextField;
    private javax.swing.JButton productTypeAdminButton;
    private mainpackage.AdminWindowPanels.ProductTypeAdminPanel productTypeAdminPanel;
    private javax.swing.JButton productsAdminButton;
    private mainpackage.AdminWindowPanels.ProductsAdminPanel productsAdminPanel;
    private javax.swing.JButton recipesAdminButton;
    private mainpackage.AdminWindowPanels.RecipesAdminPanel recipesAdminPanel;
    private javax.swing.JPasswordField repParolaContCATextField1;
    public javax.swing.JPanel rightSideAdminPanel;
    // End of variables declaration//GEN-END:variables
}
